# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage


OUTPUT_PATH = (Path(__file__).resolve().parent.parent / "Assets").resolve()

def relative_to_assets(frame: str, image:str) -> Path:
    return OUTPUT_PATH / frame / image



window = Tk()

window.geometry("1051x721")
window.configure(bg="#FFAB7C")
frame = "home_frame"

canvas = Canvas(
    window,
    bg="#FFAB7C",
    height=721,
    width=1051,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)

canvas.place(x=0, y=0)
canvas.create_rectangle(0.0, 0.0, 1051.0, 80.0, fill="#A03900", outline="")

button_image_1 = PhotoImage(file=relative_to_assets(frame,"coding.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
)
button_1.place(x=215.0, y=5.0, width=70.0, height=70.0)

button_image_2 = PhotoImage(file=relative_to_assets(frame,"figma.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
)
button_2.place(x=145.0, y=5.0, width=70.0, height=70.0)

button_image_3 = PhotoImage(file=relative_to_assets(frame,"github.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
)
button_3.place(x=75.0, y=5.0, width=70.0, height=70.0)

button_image_4 = PhotoImage(file=relative_to_assets(frame,"info.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",
)
button_4.place(x=911.0, y=651.0, width=70.0, height=70.0)

button_image_5 = PhotoImage(file=relative_to_assets(frame,"hue.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat",
)
button_5.place(x=285.0, y=5.0, width=70.0, height=70.0)

button_image_6 = PhotoImage(file=relative_to_assets(frame,"schedule.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat",
)
button_6.place(x=355.0, y=5.0, width=70.0, height=70.0)

button_image_7 = PhotoImage(file=relative_to_assets(frame,"home.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat",
)
button_7.place(x=5.0, y=5.0, width=70.0, height=70.0)

button_image_8 = PhotoImage(file=relative_to_assets(frame,"licenses.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat",
)
button_8.place(x=981.0, y=651.0, width=70.0, height=70.0)

button_image_9 = PhotoImage(file=relative_to_assets(frame,"vscode.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat",
)
button_9.place(x=425.0, y=5.0, width=70.0, height=70.0)

canvas.create_text(
    0.0,
    80.0,
    anchor="nw",
    text="Crowxar Personal Toolbox",
    fill="#000000",
    font=("Figtree ExtraBold", 80 * -1),
)

canvas.create_text(
    40.0,
    176.0,
    anchor="nw",
    text="Select an icon to get started",
    fill="#000000",
    font=("Figtree Light", 32 * -1),
)
window.resizable(False, False)
window.mainloop()